In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [2]:
cancer_data = load_breast_cancer()

In [3]:
print(cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [4]:
features = pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names)
target = pd.DataFrame(cancer_data.target, columns=['Target'])

In [5]:
features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [6]:
target.head()

Target
0       0
1       0
2       0
3       0
4       0

In [7]:
target.Target.value_counts()

1    357
0    212
Name: Target, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report

In [9]:
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=10)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(426, 30)
(143, 30)
(426, 1)
(143, 1)


In [10]:
my_logreg_model = LogisticRegression().fit(X_train, y_train)

/Users/gaganshetty/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/gaganshetty/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
my_logreg_preds_train = my_logreg_model.predict(X_train)
my_logreg_preds_test = my_logreg_model.predict(X_test)

print('Accuracy on Train set : ',accuracy_score(y_train, my_logreg_preds_train))
print('Accuracy on Test set` : ',accuracy_score(y_test, my_logreg_preds_test))
      

Accuracy on Train set :  0.9460093896713615
Accuracy on Test set` :  0.9300699300699301


In [12]:
# Prediction Probabilities
list(zip(my_logreg_model.predict_proba(X_train), my_logreg_model.predict(X_train)))

[(array([4.71928145e-04, 9.99528072e-01]), 1),
 (array([3.62257690e-04, 9.99637742e-01]), 1),
 (array([1.00000000e+00, 4.45174038e-12]), 0),
 (array([6.43100127e-05, 9.99935690e-01]), 1),
 (array([0.00473638, 0.99526362]), 1),
 (array([0.0448118, 0.9551882]), 1),
 (array([3.38595913e-05, 9.99966140e-01]), 1),
 (array([9.99941570e-01, 5.84302085e-05]), 0),
 (array([9.24192849e-05, 9.99907581e-01]), 1),
 (array([1.0000000e+00, 3.9902221e-11]), 0),
 (array([0.10257016, 0.89742984]), 1),
 (array([1.04607626e-04, 9.99895392e-01]), 1),
 (array([0.01016462, 0.98983538]), 1),
 (array([9.99999959e-01, 4.11603413e-08]), 0),
 (array([0.00115623, 0.99884377]), 1),
 (array([0.00174357, 0.99825643]), 1),
 (array([9.99947740e-01, 5.22597806e-05]), 0),
 (array([7.49483378e-04, 9.99250517e-01]), 1),
 (array([3.67328102e-05, 9.99963267e-01]), 1),
 (array([6.47749263e-04, 9.99352251e-01]), 1),
 (array([0.00155284, 0.99844716]), 1),
 (array([0.00424053, 0.99575947]), 1),
 (array([9.99945478e-01, 5.4521673

In [13]:
print('Confusion Matrix on Train set :\n', confusion_matrix(y_train, my_logreg_preds_train))

Confusion Matrix on Train set :
 [[147  13]
 [ 10 256]]


In [14]:
print('Confusion Matrix on Test set :\n', confusion_matrix(y_test, my_logreg_preds_test))

Confusion Matrix on Test set :
 [[48  4]
 [ 6 85]]


In [15]:
print('Precision on Train set : ',precision_score(y_train, my_logreg_preds_train))
print('Precision on Test set : ',precision_score(y_test, my_logreg_preds_test))

print('\n')

print('Recall on Train set : ',recall_score(y_train, my_logreg_preds_train))
print('Recall on Test set : ',recall_score(y_test, my_logreg_preds_test))

print('\n')

print('F1-Score on Train set : ',f1_score(y_train, my_logreg_preds_train))
print('F1-Score on Test set : ',f1_score(y_test, my_logreg_preds_test))

Precision on Train set :  0.9516728624535316
Precision on Test set :  0.9550561797752809


Recall on Train set :  0.9624060150375939
Recall on Test set :  0.9340659340659341


F1-Score on Train set :  0.9570093457943926
F1-Score on Test set :  0.9444444444444444


In [16]:
print('Classification Report on Train set : ')
print(classification_report(y_train, my_logreg_preds_train))

Classification Report on Train set : 
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       160
           1       0.95      0.96      0.96       266

    accuracy                           0.95       426
   macro avg       0.94      0.94      0.94       426
weighted avg       0.95      0.95      0.95       426



In [17]:
print('Classification Report on Test set : ')
print(classification_report(y_test, my_logreg_preds_test))

Classification Report on Test set : 
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        52
           1       0.96      0.93      0.94        91

    accuracy                           0.93       143
   macro avg       0.92      0.93      0.93       143
weighted avg       0.93      0.93      0.93       143

